"""initial_schema

Revision ID: ad0555a5597f
Revises:
Create Date: 2026-03-14 16:34:37.319995+05:30
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad0555a5597f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("bar_registration_number", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cnr_number", sa.String(length=25), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "case_type",
            sa.Enum(
                "PROPERTY",
                "CIVIL",
                "CRIMINAL",
                "FAMILY",
                "REVENUE",
                "MUTATION",
                "OTHER",
                name="casetype",
            ),
            nullable=False,
        ),
        sa.Column("court_name", sa.String(length=255), nullable=False),
        sa.Column("court_district", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PENDING",
                "HEARING_SCHEDULED",
                "JUDGMENT_RESERVED",
                "DISPOSED",
                "APPEALED",
                "CLOSED",
                name="casestatus",
            ),
            nullable=False,
        ),
        sa.Column("filed_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_cnr_number"), "cases", ["cnr_number"], unique=True)
    op.create_index(op.f("ix_cases_id"), "cases", ["id"], unique=False)
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_index(op.f("ix_cases_title"), "cases", ["title"], unique=False)
    op.create_index(op.f("ix_cases_user_id"), "cases", ["user_id"], unique=False)

    op.create_table(
        "legal_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum(
                "DV_ACT",
                "IPC",
                "BNS",
                "MLRC",
                "REGISTRATION_ACT",
                "TRANSFER_OF_PROPERTY",
                "CPC",
                "OTHER",
                name="legaldocumenttype",
            ),
            nullable=False,
        ),
        sa.Column("storage_path", sa.String(length=1000), nullable=False),
        sa.Column("encryption_iv", sa.String(length=64), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("total_chunks", sa.Integer(), nullable=True),
        sa.Column(
            "indexing_status",
            sa.Enum(
                "UPLOADED",
                "INDEXING",
                "INDEXED",
                "FAILED",
                "STALE",
                name="indexingstatus",
            ),
            nullable=False,
        ),
        sa.Column("embed_model", sa.String(length=100), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("jurisdiction", sa.String(length=100), nullable=False),
        sa.Column("effective_date", sa.String(length=20), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_legal_documents_doc_type"), "legal_documents", ["doc_type"], unique=False
    )
    op.create_index(op.f("ix_legal_documents_id"), "legal_documents", ["id"], unique=False)
    op.create_index(
        op.f("ix_legal_documents_indexing_status"),
        "legal_documents",
        ["indexing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_documents_short_name"), "legal_documents", ["short_name"], unique=False
    )
    op.create_index(
        op.f("ix_legal_documents_title"), "legal_documents", ["title"], unique=False
    )

    op.create_table(
        "client_statements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("audio_storage_path", sa.String(length=1000), nullable=True),
        sa.Column("audio_encryption_iv", sa.String(length=64), nullable=True),
        sa.Column("audio_duration_seconds", sa.Float(), nullable=True),
        sa.Column("audio_mime_type", sa.String(length=50), nullable=False),
        sa.Column(
            "language",
            sa.Enum(
                "MARATHI",
                "HINDI",
                "ENGLISH",
                "CODE_SWITCH",
                name="statementlanguage",
            ),
            nullable=False,
        ),
        sa.Column("transcript_raw", sa.Text(), nullable=True),
        sa.Column("transcript_clean", sa.Text(), nullable=True),
        sa.Column("sarvam_request_id", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AUDIO_UPLOADED",
                "TRANSCRIBING",
                "TRANSCRIBED",
                "FACTS_EXTRACTED",
                "DRAFT_GENERATED",
                "FAILED",
                name="statementstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_statements_case_id"), "client_statements", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_client_statements_id"), "client_statements", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_client_statements_status"), "client_statements", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_client_statements_user_id"), "client_statements", ["user_id"], unique=False
    )

    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "SEVEN_TWELVE_EXTRACT",
                "FERFAR",
                "INDEX_TWO",
                "SALE_DEED",
                "AGREEMENT_FOR_SALE",
                "COURT_ORDER",
                "VAKALATNAMA",
                "LEGAL_NOTICE",
                "AFFIDAVIT",
                "SURVEY_PLAN",
                "NA_ORDER",
                "OTHER",
                name="documenttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.Enum(
                "ENGLISH",
                "MARATHI",
                "HINDI",
                "BILINGUAL_EN_MR",
                name="documentlanguage",
            ),
            nullable=False,
        ),
        sa.Column("storage_path", sa.String(length=1000), nullable=False),
        sa.Column("encryption_iv", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "ocr_status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "SKIPPED",
                name="ocrstatus",
            ),
            nullable=False,
        ),
        sa.Column("ocr_provider", sa.String(length=50), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False)
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.create_index(
        op.f("ix_documents_ocr_status"), "documents", ["ocr_status"], unique=False
    )

    op.create_table(
        "hearings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("hearing_date", sa.Date(), nullable=False),
        sa.Column("hearing_time", sa.Time(), nullable=True),
        sa.Column("judge_name", sa.String(length=255), nullable=True),
        sa.Column("court_room", sa.String(length=50), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum(
                "ADMISSION",
                "ARGUMENTS",
                "EVIDENCE",
                "CROSS_EXAMINATION",
                "JUDGMENT",
                "INTERIM_ORDER",
                "MENTION",
                "OTHER",
                name="hearingpurpose",
            ),
            nullable=False,
        ),
        sa.Column("outcome_notes", sa.Text(), nullable=True),
        sa.Column("next_date", sa.Date(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hearings_case_id"), "hearings", ["case_id"], unique=False)
    op.create_index(op.f("ix_hearings_hearing_date"), "hearings", ["hearing_date"], unique=False)
    op.create_index(op.f("ix_hearings_id"), "hearings", ["id"], unique=False)
    op.create_index(op.f("ix_hearings_next_date"), "hearings", ["next_date"], unique=False)

    op.create_table(
        "parties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "PETITIONER",
                "RESPONDENT",
                "CLIENT",
                "WITNESS",
                "INTERVENER",
                "THIRD_PARTY",
                name="partyrole",
            ),
            nullable=False,
        ),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("contact_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("aadhar_ref", sa.String(length=4), nullable=True),
        sa.Column("is_organization", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parties_case_id"), "parties", ["case_id"], unique=False)
    op.create_index(op.f("ix_parties_id"), "parties", ["id"], unique=False)
    op.create_index(op.f("ix_parties_name"), "parties", ["name"], unique=False)

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(384), nullable=True),
        sa.Column("source_citation", sa.String(length=1000), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("embed_model", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"),
        "document_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_index(op.f("ix_document_chunks_id"), "document_chunks", ["id"], unique=False)

    op.create_table(
        "draft_petitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "facts_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "legal_sections_used",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "template_ids_used",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("draft_text", sa.Text(), nullable=False),
        sa.Column("disclaimer", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "GENERATING",
                "DRAFT",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "ARCHIVED",
                name="draftstatus",
            ),
            nullable=False,
        ),
        sa.Column("lawyer_feedback", sa.Text(), nullable=True),
        sa.Column("generation_model", sa.String(length=100), nullable=False),
        sa.Column("generation_prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"]),
        sa.ForeignKeyConstraint(["statement_id"], ["client_statements.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_draft_petitions_case_id"), "draft_petitions", ["case_id"], unique=False
    )
    op.create_index(op.f("ix_draft_petitions_id"), "draft_petitions", ["id"], unique=False)
    op.create_index(
        op.f("ix_draft_petitions_statement_id"),
        "draft_petitions",
        ["statement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_draft_petitions_status"), "draft_petitions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_draft_petitions_user_id"), "draft_petitions", ["user_id"], unique=False
    )

    op.create_table(
        "lawyer_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "template_type",
            sa.Enum(
                "DV_PETITION",
                "DV_PROTECTION_ORDER",
                "DV_RESIDENCE_ORDER",
                "DV_MONETARY_RELIEF",
                "DV_CUSTODY_ORDER",
                "DV_COMPENSATION",
                "GENERAL",
                name="templatetype",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(384), nullable=True),
        sa.Column("embed_model", sa.String(length=100), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("source_draft_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["source_draft_id"], ["draft_petitions.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lawyer_templates_id"), "lawyer_templates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_lawyer_templates_template_type"),
        "lawyer_templates",
        ["template_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lawyer_templates_user_id"), "lawyer_templates", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lawyer_templates_user_id"), table_name="lawyer_templates")
    op.drop_index(op.f("ix_lawyer_templates_template_type"), table_name="lawyer_templates")
    op.drop_index(op.f("ix_lawyer_templates_id"), table_name="lawyer_templates")
    op.drop_table("lawyer_templates")
    op.drop_index(op.f("ix_draft_petitions_user_id"), table_name="draft_petitions")
    op.drop_index(op.f("ix_draft_petitions_status"), table_name="draft_petitions")
    op.drop_index(op.f("ix_draft_petitions_statement_id"), table_name="draft_petitions")
    op.drop_index(op.f("ix_draft_petitions_id"), table_name="draft_petitions")
    op.drop_index(op.f("ix_draft_petitions_case_id"), table_name="draft_petitions")
    op.drop_table("draft_petitions")
    op.drop_index(op.f("ix_document_chunks_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_parties_name"), table_name="parties")
    op.drop_index(op.f("ix_parties_id"), table_name="parties")
    op.drop_index(op.f("ix_parties_case_id"), table_name="parties")
    op.drop_table("parties")
    op.drop_index(op.f("ix_hearings_next_date"), table_name="hearings")
    op.drop_index(op.f("ix_hearings_id"), table_name="hearings")
    op.drop_index(op.f("ix_hearings_hearing_date"), table_name="hearings")
    op.drop_index(op.f("ix_hearings_case_id"), table_name="hearings")
    op.drop_table("hearings")
    op.drop_index(op.f("ix_documents_ocr_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_case_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_client_statements_user_id"), table_name="client_statements")
    op.drop_index(op.f("ix_client_statements_status"), table_name="client_statements")
    op.drop_index(op.f("ix_client_statements_id"), table_name="client_statements")
    op.drop_index(op.f("ix_client_statements_case_id"), table_name="client_statements")
    op.drop_table("client_statements")
    op.drop_index(op.f("ix_legal_documents_title"), table_name="legal_documents")
    op.drop_index(op.f("ix_legal_documents_short_name"), table_name="legal_documents")
    op.drop_index(op.f("ix_legal_documents_indexing_status"), table_name="legal_documents")
    op.drop_index(op.f("ix_legal_documents_id"), table_name="legal_documents")
    op.drop_index(op.f("ix_legal_documents_doc_type"), table_name="legal_documents")
    op.drop_table("legal_documents")
    op.drop_index(op.f("ix_cases_user_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_title"), table_name="cases")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index(op.f("ix_cases_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_cnr_number"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###